name: Update Dynamic Content

on:
  schedule:
    # Runs every 5 minutes for Spotify and every 30 minutes for WakaTime
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-wakatime-stats:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@v4
        with:
          # Required: Your WakaTime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Required: Your WakaTime username
          WAKATIME_USERNAME: "[YOUR_WAKATIME_USERNAME]"
          # Required: Your GitHub username
          GH_USERNAME: "[YOUR_USERNAME]"
          # Optional: The languages to display
          LANG_COUNT: 10
          # Optional: Show your coding time by day
          SHOW_DAYS_OF_WEEK: "True"
          # Optional: The theme to use
          THEME: "gotham"
          
  update-spotify-listening:
    name: Update Spotify Listening
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update README with Spotify listening
        uses: kittinan/spotify-github-profile@v1
        with:
          # Required: Your Spotify refresh token
          REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          # Required: Your Spotify client ID
          CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          # Required: Your Spotify client secret
          CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          # Optional: The market to use for Spotify
          MARKET: "US"
          # Optional: The theme to use
          THEME: "dark"
